name: salamapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  adhan: ^2.0.0+1
  intl: ^0.18.0
  location: ^4.4.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^12.0.3
  external_app_launcher: ^3.1.0
  quran: ^1.1.4
  audioplayers: ^1.1.1
  url_launcher: ^6.1.7
  like_button: ^2.0.5
  provider: ^6.0.4
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  http: ^0.13.5
  permission_handler: ^10.2.0
  flutter_qiblah: ^2.1.0
  shared_preferences: ^2.0.15
  app_settings: ^4.2.0
  open_mail_app: ^0.4.5
  table_calendar: ^3.0.9
  cloud_firestore_web: ^3.2.1
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  hijri_picker: ^3.0.0
  get: ^4.6.5
  dotted_line: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/.
     - assets/icons/.
     - assets/audio/.
     - assets/audio_json/.
     - assets/hadid_json/.
     - assets/privacy_json/.
     - assets/stock_json/.
     - assets/benefits_json/.
     - assets/podcast_json/.

  fonts:
     - family: DMSans
       fonts:
         - asset: assets/fonts/DMSans-Bold.ttf
         - asset: assets/fonts/DMSans-Medium.ttf
         - asset: assets/fonts/DMSans-Regular.ttf
